//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 05:35:11 PM CET 
//


package dsa2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dsa2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InformationRequirement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "informationRequirement");
    private final static QName _ItemDefinition_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "itemDefinition");
    private final static QName _List_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "list");
    private final static QName _OrganizationUnit_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "organizationUnit");
    private final static QName _DMNEdge_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNEdge");
    private final static QName _FunctionDefinition_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "functionDefinition");
    private final static QName _Decision_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "decision");
    private final static QName _Expression_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "expression");
    private final static QName _Invocable_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "invocable");
    private final static QName _InputData_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "inputData");
    private final static QName _AuthorityRequirement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "authorityRequirement");
    private final static QName _ContextEntry_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "contextEntry");
    private final static QName _DMNStyle_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNStyle");
    private final static QName _DrgElement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "drgElement");
    private final static QName _InformationItem_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "informationItem");
    private final static QName _LiteralExpression_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "literalExpression");
    private final static QName _DMNDiagram_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNDiagram");
    private final static QName _DecisionService_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "decisionService");
    private final static QName _Color_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DC/", "Color");
    private final static QName _Bounds_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DC/", "Bounds");
    private final static QName _Point_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DC/", "Point");
    private final static QName _Dimension_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DC/", "Dimension");
    private final static QName _DMNDecisionServiceDividerLine_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNDecisionServiceDividerLine");
    private final static QName _Invocation_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "invocation");
    private final static QName _Relation_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "relation");
    private final static QName _DMNShape_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNShape");
    private final static QName _KnowledgeRequirement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "knowledgeRequirement");
    private final static QName _PerformanceIndicator_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "performanceIndicator");
    private final static QName _Association_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "association");
    private final static QName _ElementCollection_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "elementCollection");
    private final static QName _TextAnnotation_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "textAnnotation");
    private final static QName _Import_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "import");
    private final static QName _Style_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DI/", "Style");
    private final static QName _DMNDiagramElement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNDiagramElement");
    private final static QName _KnowledgeSource_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "knowledgeSource");
    private final static QName _BusinessKnowledgeModel_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "businessKnowledgeModel");
    private final static QName _Definitions_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "definitions");
    private final static QName _DMNElement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "DMNElement");
    private final static QName _Context_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "context");
    private final static QName _DecisionTable_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "decisionTable");
    private final static QName _DMNDI_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNDI");
    private final static QName _DMNLabel_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/DMNDI/", "DMNLabel");
    private final static QName _NamedElement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "namedElement");
    private final static QName _Artifact_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "artifact");
    private final static QName _BusinessContextElement_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "businessContextElement");
    private final static QName _TInformationRequirementRequiredInput_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "requiredInput");
    private final static QName _TInformationRequirementRequiredDecision_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "requiredDecision");
    private final static QName _TAuthorityRequirementRequiredAuthority_QNAME = new QName("http://www.omg.org/spec/DMN/20180521/MODEL/", "requiredAuthority");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dsa2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TDMNElement }
     * 
     */
    public TDMNElement createTDMNElement() {
        return new TDMNElement();
    }

    /**
     * Create an instance of {@link TKnowledgeSource }
     * 
     */
    public TKnowledgeSource createTKnowledgeSource() {
        return new TKnowledgeSource();
    }

    /**
     * Create an instance of {@link TDRGElement }
     * 
     */
    public TDRGElement createTDRGElement() {
        return new TDRGElement();
    }

    /**
     * Create an instance of {@link TNamedElement }
     * 
     */
    public TNamedElement createTNamedElement() {
        return new TNamedElement();
    }

    /**
     * Create an instance of {@link TImport }
     * 
     */
    public TImport createTImport() {
        return new TImport();
    }

    /**
     * Create an instance of {@link TTextAnnotation }
     * 
     */
    public TTextAnnotation createTTextAnnotation() {
        return new TTextAnnotation();
    }

    /**
     * Create an instance of {@link TArtifact }
     * 
     */
    public TArtifact createTArtifact() {
        return new TArtifact();
    }

    /**
     * Create an instance of {@link TElementCollection }
     * 
     */
    public TElementCollection createTElementCollection() {
        return new TElementCollection();
    }

    /**
     * Create an instance of {@link TPerformanceIndicator }
     * 
     */
    public TPerformanceIndicator createTPerformanceIndicator() {
        return new TPerformanceIndicator();
    }

    /**
     * Create an instance of {@link TBusinessContextElement }
     * 
     */
    public TBusinessContextElement createTBusinessContextElement() {
        return new TBusinessContextElement();
    }

    /**
     * Create an instance of {@link TAssociation }
     * 
     */
    public TAssociation createTAssociation() {
        return new TAssociation();
    }

    /**
     * Create an instance of {@link TKnowledgeRequirement }
     * 
     */
    public TKnowledgeRequirement createTKnowledgeRequirement() {
        return new TKnowledgeRequirement();
    }

    /**
     * Create an instance of {@link TRelation }
     * 
     */
    public TRelation createTRelation() {
        return new TRelation();
    }

    /**
     * Create an instance of {@link TExpression }
     * 
     */
    public TExpression createTExpression() {
        return new TExpression();
    }

    /**
     * Create an instance of {@link TDecisionTable }
     * 
     */
    public TDecisionTable createTDecisionTable() {
        return new TDecisionTable();
    }

    /**
     * Create an instance of {@link TContext }
     * 
     */
    public TContext createTContext() {
        return new TContext();
    }

    /**
     * Create an instance of {@link TDefinitions }
     * 
     */
    public TDefinitions createTDefinitions() {
        return new TDefinitions();
    }

    /**
     * Create an instance of {@link TBusinessKnowledgeModel }
     * 
     */
    public TBusinessKnowledgeModel createTBusinessKnowledgeModel() {
        return new TBusinessKnowledgeModel();
    }

    /**
     * Create an instance of {@link TInvocable }
     * 
     */
    public TInvocable createTInvocable() {
        return new TInvocable();
    }

    /**
     * Create an instance of {@link TContextEntry }
     * 
     */
    public TContextEntry createTContextEntry() {
        return new TContextEntry();
    }

    /**
     * Create an instance of {@link TInputData }
     * 
     */
    public TInputData createTInputData() {
        return new TInputData();
    }

    /**
     * Create an instance of {@link TAuthorityRequirement }
     * 
     */
    public TAuthorityRequirement createTAuthorityRequirement() {
        return new TAuthorityRequirement();
    }

    /**
     * Create an instance of {@link TDecision }
     * 
     */
    public TDecision createTDecision() {
        return new TDecision();
    }

    /**
     * Create an instance of {@link TFunctionDefinition }
     * 
     */
    public TFunctionDefinition createTFunctionDefinition() {
        return new TFunctionDefinition();
    }

    /**
     * Create an instance of {@link TOrganizationUnit }
     * 
     */
    public TOrganizationUnit createTOrganizationUnit() {
        return new TOrganizationUnit();
    }

    /**
     * Create an instance of {@link TList }
     * 
     */
    public TList createTList() {
        return new TList();
    }

    /**
     * Create an instance of {@link TInformationRequirement }
     * 
     */
    public TInformationRequirement createTInformationRequirement() {
        return new TInformationRequirement();
    }

    /**
     * Create an instance of {@link TItemDefinition }
     * 
     */
    public TItemDefinition createTItemDefinition() {
        return new TItemDefinition();
    }

    /**
     * Create an instance of {@link TInvocation }
     * 
     */
    public TInvocation createTInvocation() {
        return new TInvocation();
    }

    /**
     * Create an instance of {@link TDecisionService }
     * 
     */
    public TDecisionService createTDecisionService() {
        return new TDecisionService();
    }

    /**
     * Create an instance of {@link TLiteralExpression }
     * 
     */
    public TLiteralExpression createTLiteralExpression() {
        return new TLiteralExpression();
    }

    /**
     * Create an instance of {@link TInformationItem }
     * 
     */
    public TInformationItem createTInformationItem() {
        return new TInformationItem();
    }

    /**
     * Create an instance of {@link TImportedValues }
     * 
     */
    public TImportedValues createTImportedValues() {
        return new TImportedValues();
    }

    /**
     * Create an instance of {@link TUnaryTests }
     * 
     */
    public TUnaryTests createTUnaryTests() {
        return new TUnaryTests();
    }

    /**
     * Create an instance of {@link TDMNElementReference }
     * 
     */
    public TDMNElementReference createTDMNElementReference() {
        return new TDMNElementReference();
    }

    /**
     * Create an instance of {@link TInputClause }
     * 
     */
    public TInputClause createTInputClause() {
        return new TInputClause();
    }

    /**
     * Create an instance of {@link TRuleAnnotationClause }
     * 
     */
    public TRuleAnnotationClause createTRuleAnnotationClause() {
        return new TRuleAnnotationClause();
    }

    /**
     * Create an instance of {@link TRuleAnnotation }
     * 
     */
    public TRuleAnnotation createTRuleAnnotation() {
        return new TRuleAnnotation();
    }

    /**
     * Create an instance of {@link TDecisionRule }
     * 
     */
    public TDecisionRule createTDecisionRule() {
        return new TDecisionRule();
    }

    /**
     * Create an instance of {@link TOutputClause }
     * 
     */
    public TOutputClause createTOutputClause() {
        return new TOutputClause();
    }

    /**
     * Create an instance of {@link TBinding }
     * 
     */
    public TBinding createTBinding() {
        return new TBinding();
    }

    /**
     * Create an instance of {@link DMNShape }
     * 
     */
    public DMNShape createDMNShape() {
        return new DMNShape();
    }

    /**
     * Create an instance of {@link DMNDiagram }
     * 
     */
    public DMNDiagram createDMNDiagram() {
        return new DMNDiagram();
    }

    /**
     * Create an instance of {@link DMNDI }
     * 
     */
    public DMNDI createDMNDI() {
        return new DMNDI();
    }

    /**
     * Create an instance of {@link DMNDecisionServiceDividerLine }
     * 
     */
    public DMNDecisionServiceDividerLine createDMNDecisionServiceDividerLine() {
        return new DMNDecisionServiceDividerLine();
    }

    /**
     * Create an instance of {@link DMNLabel }
     * 
     */
    public DMNLabel createDMNLabel() {
        return new DMNLabel();
    }

    /**
     * Create an instance of {@link DMNEdge }
     * 
     */
    public DMNEdge createDMNEdge() {
        return new DMNEdge();
    }

    /**
     * Create an instance of {@link DMNStyle }
     * 
     */
    public DMNStyle createDMNStyle() {
        return new DMNStyle();
    }

    /**
     * Create an instance of {@link Color }
     * 
     */
    public Color createColor() {
        return new Color();
    }

    /**
     * Create an instance of {@link Bounds }
     * 
     */
    public Bounds createBounds() {
        return new Bounds();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link DiagramElement.Extension }
     * 
     */
    public DiagramElement.Extension createDiagramElementExtension() {
        return new DiagramElement.Extension();
    }

    /**
     * Create an instance of {@link Style.Extension }
     * 
     */
    public Style.Extension createStyleExtension() {
        return new Style.Extension();
    }

    /**
     * Create an instance of {@link TDMNElement.ExtensionElements }
     * 
     */
    public TDMNElement.ExtensionElements createTDMNElementExtensionElements() {
        return new TDMNElement.ExtensionElements();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformationRequirement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "informationRequirement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "DMNElement")
    public JAXBElement<TInformationRequirement> createInformationRequirement(TInformationRequirement value) {
        return new JAXBElement<TInformationRequirement>(_InformationRequirement_QNAME, TInformationRequirement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TItemDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "itemDefinition", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "namedElement")
    public JAXBElement<TItemDefinition> createItemDefinition(TItemDefinition value) {
        return new JAXBElement<TItemDefinition>(_ItemDefinition_QNAME, TItemDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "list", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TList> createList(TList value) {
        return new JAXBElement<TList>(_List_QNAME, TList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOrganizationUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "organizationUnit", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "businessContextElement")
    public JAXBElement<TOrganizationUnit> createOrganizationUnit(TOrganizationUnit value) {
        return new JAXBElement<TOrganizationUnit>(_OrganizationUnit_QNAME, TOrganizationUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNEdge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNEdge", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", substitutionHeadName = "DMNDiagramElement")
    public JAXBElement<DMNEdge> createDMNEdge(DMNEdge value) {
        return new JAXBElement<DMNEdge>(_DMNEdge_QNAME, DMNEdge.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFunctionDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "functionDefinition", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TFunctionDefinition> createFunctionDefinition(TFunctionDefinition value) {
        return new JAXBElement<TFunctionDefinition>(_FunctionDefinition_QNAME, TFunctionDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "decision", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "drgElement")
    public JAXBElement<TDecision> createDecision(TDecision value) {
        return new JAXBElement<TDecision>(_Decision_QNAME, TDecision.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "expression")
    public JAXBElement<TExpression> createExpression(TExpression value) {
        return new JAXBElement<TExpression>(_Expression_QNAME, TExpression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInvocable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "invocable", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "drgElement")
    public JAXBElement<TInvocable> createInvocable(TInvocable value) {
        return new JAXBElement<TInvocable>(_Invocable_QNAME, TInvocable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInputData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "inputData", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "drgElement")
    public JAXBElement<TInputData> createInputData(TInputData value) {
        return new JAXBElement<TInputData>(_InputData_QNAME, TInputData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAuthorityRequirement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "authorityRequirement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "DMNElement")
    public JAXBElement<TAuthorityRequirement> createAuthorityRequirement(TAuthorityRequirement value) {
        return new JAXBElement<TAuthorityRequirement>(_AuthorityRequirement_QNAME, TAuthorityRequirement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TContextEntry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "contextEntry", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "DMNElement")
    public JAXBElement<TContextEntry> createContextEntry(TContextEntry value) {
        return new JAXBElement<TContextEntry>(_ContextEntry_QNAME, TContextEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNStyle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNStyle", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/DI/", substitutionHeadName = "Style")
    public JAXBElement<DMNStyle> createDMNStyle(DMNStyle value) {
        return new JAXBElement<DMNStyle>(_DMNStyle_QNAME, DMNStyle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDRGElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "drgElement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "namedElement")
    public JAXBElement<TDRGElement> createDrgElement(TDRGElement value) {
        return new JAXBElement<TDRGElement>(_DrgElement_QNAME, TDRGElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInformationItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "informationItem", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "namedElement")
    public JAXBElement<TInformationItem> createInformationItem(TInformationItem value) {
        return new JAXBElement<TInformationItem>(_InformationItem_QNAME, TInformationItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLiteralExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "literalExpression", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TLiteralExpression> createLiteralExpression(TLiteralExpression value) {
        return new JAXBElement<TLiteralExpression>(_LiteralExpression_QNAME, TLiteralExpression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNDiagram }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNDiagram")
    public JAXBElement<DMNDiagram> createDMNDiagram(DMNDiagram value) {
        return new JAXBElement<DMNDiagram>(_DMNDiagram_QNAME, DMNDiagram.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecisionService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "decisionService", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "invocable")
    public JAXBElement<TDecisionService> createDecisionService(TDecisionService value) {
        return new JAXBElement<TDecisionService>(_DecisionService_QNAME, TDecisionService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Color }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DC/", name = "Color")
    public JAXBElement<Color> createColor(Color value) {
        return new JAXBElement<Color>(_Color_QNAME, Color.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Bounds }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DC/", name = "Bounds")
    public JAXBElement<Bounds> createBounds(Bounds value) {
        return new JAXBElement<Bounds>(_Bounds_QNAME, Bounds.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Point }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DC/", name = "Point")
    public JAXBElement<Point> createPoint(Point value) {
        return new JAXBElement<Point>(_Point_QNAME, Point.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dimension }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DC/", name = "Dimension")
    public JAXBElement<Dimension> createDimension(Dimension value) {
        return new JAXBElement<Dimension>(_Dimension_QNAME, Dimension.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNDecisionServiceDividerLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNDecisionServiceDividerLine")
    public JAXBElement<DMNDecisionServiceDividerLine> createDMNDecisionServiceDividerLine(DMNDecisionServiceDividerLine value) {
        return new JAXBElement<DMNDecisionServiceDividerLine>(_DMNDecisionServiceDividerLine_QNAME, DMNDecisionServiceDividerLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInvocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "invocation", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TInvocation> createInvocation(TInvocation value) {
        return new JAXBElement<TInvocation>(_Invocation_QNAME, TInvocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRelation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "relation", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TRelation> createRelation(TRelation value) {
        return new JAXBElement<TRelation>(_Relation_QNAME, TRelation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNShape", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", substitutionHeadName = "DMNDiagramElement")
    public JAXBElement<DMNShape> createDMNShape(DMNShape value) {
        return new JAXBElement<DMNShape>(_DMNShape_QNAME, DMNShape.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TKnowledgeRequirement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "knowledgeRequirement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "DMNElement")
    public JAXBElement<TKnowledgeRequirement> createKnowledgeRequirement(TKnowledgeRequirement value) {
        return new JAXBElement<TKnowledgeRequirement>(_KnowledgeRequirement_QNAME, TKnowledgeRequirement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPerformanceIndicator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "performanceIndicator", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "businessContextElement")
    public JAXBElement<TPerformanceIndicator> createPerformanceIndicator(TPerformanceIndicator value) {
        return new JAXBElement<TPerformanceIndicator>(_PerformanceIndicator_QNAME, TPerformanceIndicator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAssociation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "association", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "artifact")
    public JAXBElement<TAssociation> createAssociation(TAssociation value) {
        return new JAXBElement<TAssociation>(_Association_QNAME, TAssociation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TElementCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "elementCollection", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "namedElement")
    public JAXBElement<TElementCollection> createElementCollection(TElementCollection value) {
        return new JAXBElement<TElementCollection>(_ElementCollection_QNAME, TElementCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTextAnnotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "textAnnotation", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "artifact")
    public JAXBElement<TTextAnnotation> createTextAnnotation(TTextAnnotation value) {
        return new JAXBElement<TTextAnnotation>(_TextAnnotation_QNAME, TTextAnnotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TImport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "import", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "namedElement")
    public JAXBElement<TImport> createImport(TImport value) {
        return new JAXBElement<TImport>(_Import_QNAME, TImport.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Style }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DI/", name = "Style")
    public JAXBElement<Style> createStyle(Style value) {
        return new JAXBElement<Style>(_Style_QNAME, Style.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiagramElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNDiagramElement")
    public JAXBElement<DiagramElement> createDMNDiagramElement(DiagramElement value) {
        return new JAXBElement<DiagramElement>(_DMNDiagramElement_QNAME, DiagramElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TKnowledgeSource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "knowledgeSource", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "drgElement")
    public JAXBElement<TKnowledgeSource> createKnowledgeSource(TKnowledgeSource value) {
        return new JAXBElement<TKnowledgeSource>(_KnowledgeSource_QNAME, TKnowledgeSource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBusinessKnowledgeModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "businessKnowledgeModel", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "invocable")
    public JAXBElement<TBusinessKnowledgeModel> createBusinessKnowledgeModel(TBusinessKnowledgeModel value) {
        return new JAXBElement<TBusinessKnowledgeModel>(_BusinessKnowledgeModel_QNAME, TBusinessKnowledgeModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "definitions", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "namedElement")
    public JAXBElement<TDefinitions> createDefinitions(TDefinitions value) {
        return new JAXBElement<TDefinitions>(_Definitions_QNAME, TDefinitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDMNElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "DMNElement")
    public JAXBElement<TDMNElement> createDMNElement(TDMNElement value) {
        return new JAXBElement<TDMNElement>(_DMNElement_QNAME, TDMNElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "context", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TContext> createContext(TContext value) {
        return new JAXBElement<TContext>(_Context_QNAME, TContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecisionTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "decisionTable", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "expression")
    public JAXBElement<TDecisionTable> createDecisionTable(TDecisionTable value) {
        return new JAXBElement<TDecisionTable>(_DecisionTable_QNAME, TDecisionTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNDI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNDI")
    public JAXBElement<DMNDI> createDMNDI(DMNDI value) {
        return new JAXBElement<DMNDI>(_DMNDI_QNAME, DMNDI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DMNLabel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/DMNDI/", name = "DMNLabel")
    public JAXBElement<DMNLabel> createDMNLabel(DMNLabel value) {
        return new JAXBElement<DMNLabel>(_DMNLabel_QNAME, DMNLabel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNamedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "namedElement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "DMNElement")
    public JAXBElement<TNamedElement> createNamedElement(TNamedElement value) {
        return new JAXBElement<TNamedElement>(_NamedElement_QNAME, TNamedElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TArtifact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "artifact", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", substitutionHeadName = "DMNElement")
    public JAXBElement<TArtifact> createArtifact(TArtifact value) {
        return new JAXBElement<TArtifact>(_Artifact_QNAME, TArtifact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBusinessContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "businessContextElement")
    public JAXBElement<TBusinessContextElement> createBusinessContextElement(TBusinessContextElement value) {
        return new JAXBElement<TBusinessContextElement>(_BusinessContextElement_QNAME, TBusinessContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "requiredInput", scope = TInformationRequirement.class)
    public JAXBElement<TDMNElementReference> createTInformationRequirementRequiredInput(TDMNElementReference value) {
        return new JAXBElement<TDMNElementReference>(_TInformationRequirementRequiredInput_QNAME, TDMNElementReference.class, TInformationRequirement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "requiredDecision", scope = TInformationRequirement.class)
    public JAXBElement<TDMNElementReference> createTInformationRequirementRequiredDecision(TDMNElementReference value) {
        return new JAXBElement<TDMNElementReference>(_TInformationRequirementRequiredDecision_QNAME, TDMNElementReference.class, TInformationRequirement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "requiredInput", scope = TAuthorityRequirement.class)
    public JAXBElement<TDMNElementReference> createTAuthorityRequirementRequiredInput(TDMNElementReference value) {
        return new JAXBElement<TDMNElementReference>(_TInformationRequirementRequiredInput_QNAME, TDMNElementReference.class, TAuthorityRequirement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "requiredAuthority", scope = TAuthorityRequirement.class)
    public JAXBElement<TDMNElementReference> createTAuthorityRequirementRequiredAuthority(TDMNElementReference value) {
        return new JAXBElement<TDMNElementReference>(_TAuthorityRequirementRequiredAuthority_QNAME, TDMNElementReference.class, TAuthorityRequirement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", name = "requiredDecision", scope = TAuthorityRequirement.class)
    public JAXBElement<TDMNElementReference> createTAuthorityRequirementRequiredDecision(TDMNElementReference value) {
        return new JAXBElement<TDMNElementReference>(_TInformationRequirementRequiredDecision_QNAME, TDMNElementReference.class, TAuthorityRequirement.class, value);
    }

}
