//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 05:35:11 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dsa2;
