//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 05:35:11 PM CET 
//


package dsa2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAuthorityRequirement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAuthorityRequirement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20180521/MODEL/}tDMNElement">
 *       &lt;choice>
 *         &lt;element name="requiredDecision" type="{http://www.omg.org/spec/DMN/20180521/MODEL/}tDMNElementReference"/>
 *         &lt;element name="requiredInput" type="{http://www.omg.org/spec/DMN/20180521/MODEL/}tDMNElementReference"/>
 *         &lt;element name="requiredAuthority" type="{http://www.omg.org/spec/DMN/20180521/MODEL/}tDMNElementReference"/>
 *       &lt;/choice>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAuthorityRequirement", propOrder = {
    "requiredDecisionOrRequiredInputOrRequiredAuthority"
})
public class TAuthorityRequirement
    extends TDMNElement
{

    @XmlElementRefs({
        @XmlElementRef(name = "requiredInput", namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "requiredDecision", namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "requiredAuthority", namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", type = JAXBElement.class, required = false)
    })
    protected JAXBElement<TDMNElementReference> requiredDecisionOrRequiredInputOrRequiredAuthority;

    /**
     * Gets the value of the requiredDecisionOrRequiredInputOrRequiredAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}
     *     {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}
     *     {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}
     *     
     */
    public JAXBElement<TDMNElementReference> getRequiredDecisionOrRequiredInputOrRequiredAuthority() {
        return requiredDecisionOrRequiredInputOrRequiredAuthority;
    }

    /**
     * Sets the value of the requiredDecisionOrRequiredInputOrRequiredAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}
     *     {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}
     *     {@link JAXBElement }{@code <}{@link TDMNElementReference }{@code >}
     *     
     */
    public void setRequiredDecisionOrRequiredInputOrRequiredAuthority(JAXBElement<TDMNElementReference> value) {
        this.requiredDecisionOrRequiredInputOrRequiredAuthority = value;
    }

}
