//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 05:35:11 PM CET 
//


package dsa2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tOutputClause complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOutputClause">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20180521/MODEL/}tDMNElement">
 *       &lt;sequence>
 *         &lt;element name="outputValues" type="{http://www.omg.org/spec/DMN/20180521/MODEL/}tUnaryTests" minOccurs="0"/>
 *         &lt;element name="defaultOutputEntry" type="{http://www.omg.org/spec/DMN/20180521/MODEL/}tLiteralExpression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="typeRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOutputClause", propOrder = {
    "outputValues",
    "defaultOutputEntry"
})
public class TOutputClause
    extends TDMNElement
{

    protected TUnaryTests outputValues;
    protected TLiteralExpression defaultOutputEntry;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "typeRef")
    protected String typeRef;

    /**
     * Gets the value of the outputValues property.
     * 
     * @return
     *     possible object is
     *     {@link TUnaryTests }
     *     
     */
    public TUnaryTests getOutputValues() {
        return outputValues;
    }

    /**
     * Sets the value of the outputValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUnaryTests }
     *     
     */
    public void setOutputValues(TUnaryTests value) {
        this.outputValues = value;
    }

    /**
     * Gets the value of the defaultOutputEntry property.
     * 
     * @return
     *     possible object is
     *     {@link TLiteralExpression }
     *     
     */
    public TLiteralExpression getDefaultOutputEntry() {
        return defaultOutputEntry;
    }

    /**
     * Sets the value of the defaultOutputEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLiteralExpression }
     *     
     */
    public void setDefaultOutputEntry(TLiteralExpression value) {
        this.defaultOutputEntry = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the typeRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeRef() {
        return typeRef;
    }

    /**
     * Sets the value of the typeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeRef(String value) {
        this.typeRef = value;
    }

}
