//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 04:30:29 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DMN/20180521/MODEL/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
                                     xmlns = {
                                              @javax.xml.bind.annotation.XmlNs(prefix = "xs", namespaceURI = "http://www.w3.org/2001/XMLSchema"),
                                              @XmlNs(prefix = "", namespaceURI = "http://www.omg.org/spec/DMN/20180521/MODEL/")
                                     })
package asd;

import javax.xml.bind.annotation.XmlNs;
